version: '3.8'

# apiv2.sisnato.com.br

services:
  backend:
    image: sys_nato_back_prod_v2:0.0.1
    restart: unless-stopped
    build:
      context: .
    ports:
      - '7877:7877'
    deploy:
      replicas: 1 # Aumentando o número de réplicas para 10
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 4g
        reservations:
          cpus: '1'
          memory: 2g

  otel-collector:
    hostname: otel-collector
    image: docker.io/otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./src/infra/monitoring/otel-collector-config.yml:/etc/otel-collector-config.yml
    restart: unless-stopped
    ports:
      - '8888:8888' # Prometheus metrics exporter
      - '8889:8889' # OpenTelemetry metrics exporter
      - '4317:4317' # Porta padrão para receber telemetria via OTLP/HTTP
    depends_on:
      - prometheus

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning #https://grafana.com/docs/grafana/latest/administration/provisioning/
      - ./data/grafana-data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro

    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app

    depends_on:
      - otel-collector
      - prometheus

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=otlp-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
    ports:
      - '9091:9090'
    volumes:
      - ./src/infra/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - /etc/localtime:/etc/localtime:ro
      - ./data/prometheus-data:/prometheus
    restart: unless-stopped
